[package]
name = "codesize"
version = "0.1.0"
authors = ["Joe Frikker <jfrikker@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "=1.0.4"
clap = "2.33"
git2 = "0.9"
quick-error = "1.2"
walkdir = "2.2"